theme = "gruvbox"

[editor]
shell = ["bash", "-c"]
line-number = "relative"
bufferline = "always"
scrolloff = 5
cursorline = true
auto-format = true
true-color = true
# rulers = [80]
auto-save = false
auto-completion = true
color-modes = true
# end-of-line-diagnostics = "info"

# [editor.inline-diagnostics]
# cursor-line = "info"
# other-lines = "info"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
skip-levels = 0
character = "▏"

[editor.lsp]
enable = true
auto-signature-help = true
display-messages = true
snippets = true
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner", "spacer", "file-name"]
center = []
right = [
  "version-control",
  "spacer",
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "total-line-numbers",
  "register",
  "spacer",
]
# separator = "▏"
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"


### Experimentss

## Keybindings

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
X = "extend_line_above"

[keys.normal."]"]
"]" = "goto_next_buffer"

[keys.normal."["]
"[" = "goto_previous_buffer"
