[[language]]
name = "c"
language-servers = [ "clangd" ]
formatter = { command = "clang-format", args = ["-"] }

[[language]]
name = "java"
auto-format = true


###############################################
#                  Python                     #
###############################################

[[language]]
name = "python"
scope = "source.python"
language-servers = [ "pylsp" ]
auto-format = true
formatter = { command = "ruff", args = [ "format", "-" ] }

[language-server.pyright.config.python.analysis]
typeCheckingMode = "strict"


[language-server.pylsp.config.pylsp.plugins]
mypy = { enabled = true, strict = true }
autopep8 = { enabled = true }
rope = { enabled = true }
mccabe = { enabled = true }
flake8 = {enabled = true, ignore = ["E501"]}
pycodestyle = { enabled = false }
pyflakes = { enabled = false }
pylint = { enabled = false }
yapf = { enabled = false }
ruff = { enabled = false }

###############################################


[[language]]
name = "rust"
language-servers = [{name="rust-analyzer"}]


# Web Development
[langauge-server.typescript-language-server]
command = "typescript-language-server"

[[language]]
name = "typescript"
language-servers = [ { name="typescript-language-server" } ] 
formatter = { command = "dprint", args = [ "fmt", "--stdin", "typescript" ] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ { name="typescript-language-server" } ] 
formatter = { command = "dprint", args = [ "fmt", "--stdin", "javascript" ] }
auto-format = true

