###########
# Web Dev #
###########
[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "tailwindcss-ls"]
auto-format = true

[[language]]
name = "css"
language-servers = ["vscode-css-language-server", "tailwindcss-ls"]
auto-format = true

[[language]]
name = "jsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]
auto-format = true

[[language]]
name = "tsx"
language-servers = ["typescript-language-server", "tailwindcss-ls"]
auto-format = true

[[language]]
name = "svelte"
language-servers = ["svelteserver", "tailwindcss-ls"]
auto-format = true

[[lua]]
name = "lua"
formatter = { command = "stylua", args = ["-"] }
auto-format = true

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt", "-"] }

[language-server.clangd]
command = "clangd"

[[language]]
name = "c"
language-servers = ["clangd"]
formatter = { command = "clang-format", args = ["--style=GNU", "-"] }
auto-format = true

[[language]]
name = "cpp"
language-servers = ["clangd"]
formatter = { command = "clang-format", args = ["--style=GNU", "-"] }
auto-format = true


[[language]]
name = "java"
auto-format = true


###############################################
#                  Python                     #
###############################################

[[language]]
name = "python"
scope = "source.python"
language-servers = ["pyright"]
auto-format = true
formatter = { command = "ruff", args = ["format", "-"] }

# [language-server.pylsp.config.pylsp.plugins]
# mypy = { enabled = true, strict = true }
# autopep8 = { enabled = true }
# rope = { enabled = true }
# mccabe = { enabled = true }
# flake8 = { enabled = true, ignore = ["E501"] }
# pycodestyle = { enabled = false }
# pyflakes = { enabled = false }
# pylint = { enabled = false }
# yapf = { enabled = false }
# ruff = { enabled = false }

###############################################


[[language]]
name = "rust"
language-servers = [{ name = "rust-analyzer" }]


# Web Development
[langauge-server.typescript-language-server]
command = "typescript-language-server"

[[language]]
name = "typescript"
language-servers = [{ name = "typescript-language-server" }]
formatter = { command = "dprint", args = ["fmt", "--stdin", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [{ name = "typescript-language-server" }]
formatter = { command = "dprint", args = ["fmt", "--stdin", "javascript"] }
auto-format = true
